### ISSUE TITLE
Cannot change study description

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/csis-technical-validation#56] opened 2020-06-22 12:08 UTC
URL: [https://csis.myclimateservice.eu/study/171/view/intro](url)
Date: 22.06.2020
OS: Windows 10, 64-Bit, Firefox 77.0.1.(64-Bit)
Description: In "Introduction" tab: When I click on the "Change Description" button 

![grafik](https://user-images.githubusercontent.com/41750112/85286107-4ee3d380-b492-11ea-924c-8bb980d997b6.png)

I get the following error in the console:

`
AjaxError: 
An AJAX HTTP error occurred.
HTTP Result Code: 403
Debugging information follows.
Path: /group/171/edit/introduction?destination=/study/171/view/intro
StatusText: Forbidden
ResponseText: {"message":"The \u0027use group.introduction form mode\u0027 permission is required."} 3 js_wtlyDa6K7DGIgpUBapJHHsOdb5rPzxSO2Bk1Bb6tlKQ.js:552:32
`

**Comment by p-a-s-c-a-l** [comment] 2020-06-23 06:04
duplicate of https://github.com/clarity-h2020/csis-technical-validation/issues/51#issuecomment-647479198

**Closed by p-a-s-c-a-l** 2020-06-23 06:04 UTC
Labels: duplicate

**Comment by Itsman-AT** [comment] 2020-06-23 07:20
@p-a-s-c-a-l : Yes, sorry, forgot to remove that yesterday. Thanks.
